/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddModal: typeof import('./src/components/query/components/AddModal.vue')['default']
    AniRoute: typeof import('./src/components/ANi/AniRoute.vue')['default']
    BaseCard: typeof import('./src/components/controller/components/BaseCard.vue')['default']
    ControllerRoute: typeof import('./src/components/controller/ControllerRoute.vue')['default']
    CpuCard: typeof import('./src/components/controller/components/CpuCard.vue')['default']
    DiskCard: typeof import('./src/components/controller/components/DiskCard.vue')['default']
    DisplayModal: typeof import('./src/components/query/components/DisplayModal.vue')['default']
    DSXMenu: typeof import('./src/components/dsx-menu/DSXMenu.vue')['default']
    DSXMenuItem: typeof import('./src/components/dsx-menu/components/DSXMenuItem.vue')['default']
    FeeCalculator: typeof import('./src/components/fjrc/FeeCalculator.vue')['default']
    Fjrc: typeof import('./src/components/fjrc/Fjrc.vue')['default']
    FjrcIndex: typeof import('./src/components/fjrc/FjrcIndex.vue')['default']
    FjrcTopic: typeof import('./src/components/fjrc/FjrcTopic.vue')['default']
    FjrcTopicRoute: typeof import('./src/components/fjrc/FjrcTopicRoute.vue')['default']
    IndexButtonList: typeof import('./src/components/fjrc/IndexButtonList.vue')['default']
    IndexRoute: typeof import('./src/components/index/IndexRoute.vue')['default']
    LoginRoute: typeof import('./src/components/login/LoginRoute.vue')['default']
    LogMonitor: typeof import('./src/components/log/components/LogMonitor.vue')['default']
    LogRoute: typeof import('./src/components/log/LogRoute.vue')['default']
    MemoryCard: typeof import('./src/components/controller/components/MemoryCard.vue')['default']
    MySwitch: typeof import('./src/components/v2ray/components/MySwitch.vue')['default']
    NetworkCard: typeof import('./src/components/controller/components/NetworkCard.vue')['default']
    NotFound: typeof import('./src/components/error/NotFound.vue')['default']
    QueryRoute: typeof import('./src/components/query/QueryRoute.vue')['default']
    QueryTd: typeof import('./src/components/query/components/QueryTd.vue')['default']
    RegisterRoute: typeof import('./src/components/register/RegisterRoute.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateModal: typeof import('./src/components/query/components/UpdateModal.vue')['default']
    UpdatePwdModal: typeof import('./src/components/index/components/UpdatePwdModal.vue')['default']
    V2rayRoute: typeof import('./src/components/v2ray/V2rayRoute.vue')['default']
    WelcomeRoute: typeof import('./src/components/welcome/WelcomeRoute.vue')['default']
  }
}
