// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AddModal: typeof import('./src/components/query/AddModal.vue')['default']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    ADescriptionsItem: typeof import('@arco-design/web-vue')['DescriptionsItem']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APageHeader: typeof import('@arco-design/web-vue')['PageHeader']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    AStatistic: typeof import('@arco-design/web-vue')['Statistic']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATable: typeof import('@arco-design/web-vue')['Table']
    BaseCard: typeof import('./src/components/controller/BaseCard.vue')['default']
    ControllerRoute: typeof import('./src/components/controller/ControllerRoute.vue')['default']
    CpuCard: typeof import('./src/components/controller/CpuCard.vue')['default']
    DiskCard: typeof import('./src/components/controller/DiskCard.vue')['default']
    IndexRoute: typeof import('./src/components/IndexRoute.vue')['default']
    LoginRoute: typeof import('./src/components/LoginRoute.vue')['default']
    LogRoute: typeof import('./src/components/LogRoute.vue')['default']
    MemoryCard: typeof import('./src/components/controller/MemoryCard.vue')['default']
    MySwitch: typeof import('./src/components/v2ray/MySwitch.vue')['default']
    NetworkCard: typeof import('./src/components/controller/NetworkCard.vue')['default']
    QueryRoute: typeof import('./src/components/query/QueryRoute.vue')['default']
    RegisterRoute: typeof import('./src/components/RegisterRoute.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateModal: typeof import('./src/components/query/UpdateModal.vue')['default']
    UpdatePwdRoute: typeof import('./src/components/UpdatePwdRoute.vue')['default']
    V2rayRoute: typeof import('./src/components/v2ray/V2rayRoute.vue')['default']
    WelcomeRoute: typeof import('./src/components/WelcomeRoute.vue')['default']
  }
}
